# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naive_b', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=64)),
                ('stopw', models.CharField(max_length=1024)),
                ('symb', models.CharField(max_length=512)),
                ('normal', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('label', models.CharField(max_length=64)),
            ],
        ),
    ]
